//애플리 케이션 메인클래스
// => 애플리 케이션을 실행 할때 이 클래스를 실행한다.
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.java.application;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
